units:
  # Proxy Spacing
  kx: cx
  ky: cy
  # Padding
  m: 4
  px: kx + m
  py: ky + m
  # Double paddding
  dpx: kx + 2m
  dpy: ky + 2m
  # Preview
  $default_width: cx
  $default_height: cy
  # M2 screws
  screwSize: 1
  moutingHoleSize: 4.1
  # Other
  pcbThickness: 1.57
  baseThickness: 1.2
  caseThickness: 7.4
  choc_plate_thickness: 1.2
  fillet: 2
points:
  zones:
    main:
      #KiCAD placement
      anchor:
        shift: [100,-100]
      key:
        padding: 1ky
        spread: 1kx+2
      columns:
        outer:
          key.column_net: P4
        pinky:
          key.column_net: P5
        ring:
          key:
            stagger: 10
            splay: -4
            column_net: P6
        middle:
          key:
            column_net: P7
            stagger: 5
        index:
          key:
            column_net: P8
            stagger: -5
        inner:
          key:
            column_net: P9
            splay: -4
            stagger: -5
      rows:
        bot:
          row_net: P19
        mid:
          row_net: P20
        top:
          row_net: P21
    thumb:
      key:
        padding: 1ky
        spread: kx + 2
        splay: -10
      anchor:
        ref: main_ring_bot
        shift: [0.5kx, -1.5ky]
      columns:
        1:
          rows:
            high:
              skip: true
          key:
            column_net: P7
            splay: 0
        2:
          key.column_net: P8
          rows:
            high:
              skip: true
        3:
          key.column_net: P9
          rows:
            high:
              skip: true
        4:
          key.column_net: P16
        5:
          key.column_net: P10
      rows:
        low:
          row_net: P15
        high:
          row_net: P18
  rotate: 8
outlines:
  board:
    - what: polygon
      operation: stack
      points:
        - ref: main_outer_top
          shift: [-0.5px,0.5py]
        - ref: main_pinky_top
          shift: [0.5px,0.5py]
        - ref: main_ring_top
          shift: [-0.5px,0.5py]
        - ref: main_ring_top
          shift: [0.5kx,0.5py]
        - ref: main_middle_top
          shift: [-0.5px,0.5py]
        - ref: main_middle_top
          shift: [0.5px,0.5py]
        - ref: main_index_top
          shift: [-0.5kx,0.5py]
        - ref: main_index_top
          shift: [0.5px,0.5py]
        - ref: main_inner_top
          shift: [-0.5px,0.5py]
        - ref: main_inner_top
          shift: [1.5px-0.5m,0.5py]
        - ref: main_inner_bot
          shift: [1.5px-  0.5m,-0.5py+m]
        - ref: thumb_5_high
          shift: [0.5px,0.5py]
        - ref: thumb_5_low
          shift: [0.5px,-0.5py]
        - ref: thumb_2_low
          shift: [0.5px, -0.5py]
        - ref: thumb_1_low
          shift: [-0.5px,-0.5py]
        - ref: main_pinky_bot
          shift: [0.5px, -0.5py]
        - ref: main_outer_bot
          shift: [-0.5px,-0.5py]
      fillet: fillet
  xlBoard:
    - what: polygon
      operation: stack
      points:
        - ref: main_outer_top
          shift: [-0.5dpx,0.5dpy]
        - ref: main_pinky_top
          shift: [0.5kx,0.5dpy]
        - ref: main_ring_top
          shift: [-0.5dpx,0.5dpy]
        - ref: main_ring_top
          shift: [0.5kx-0.5m,0.5dpy]
        - ref: main_middle_top
          shift: [-0.5dpx,0.5dpy]
        - ref: main_middle_top
          shift: [0.5dpx,0.5dpy]
        - ref: main_index_top
          shift: [-0.5kx+0.5m,0.5dpy]
        - ref: main_index_top
          shift: [0.5dpx,0.5dpy]
        - ref: main_inner_top
          shift: [-0.5dpx+m,0.5dpy]
        - ref: main_inner_top
          shift: [1.5dpx-1.5m,0.5dpy]
        - ref: main_inner_bot
          shift: [1.5px,-0.5py+1.5m]
        - ref: thumb_5_high
          shift: [0.5dpx,0.5dpy]
        - ref: thumb_5_low
          shift: [0.5dpx,-0.5dpy]
        - ref: thumb_2_low
          shift: [0.5dpx-0.5m, -0.5dpy]
        - ref: thumb_1_low
          shift: [-0.5dpx,-0.5dpy]
        - ref: main_pinky_bot
          shift: [0.5dpx-m, -0.5dpy]
        - ref: main_outer_bot
          shift: [-0.5dpx,-0.5dpy]
      fillet: fillet
  _mountingHoles:
    - what: circle
      radius: screwSize
      where:
        ref: [main_outer_top]
        shift: [0.55kx, -0.3ky]
    - what: circle
      radius: screwSize
      where:
        ref: [main_inner_top]
        shift: [-0.55kx, -0.3ky]
    - what: circle
      radius: screwSize
      where:
        ref: [main_outer_bot]
        shift: [0.55kx, -0.3ky]
    - what: circle
      radius: screwSize
      where:
        ref: [thumb_2_low]
        shift: [0.55kx, -0.3ky]
    - what: circle
      radius: screwSize
      where:
        ref: [thumb_5_high]
        shift: [-0.6kx, -0.3ky]
  _switch_cutout:
    - what: rectangle
      where: true
      asym: source
      size: 14
      bound: false
  screen_cutout:
    - what: rectangle
      where: 
        ref: main_inner_mid
        shift: [1kx+2, 7]
      asym: source
      size: [19, 43]
  switch_plate:
    [ board, -_switch_cutout, -_mountingHoles, -screen_cutout ]
  _switch_mount_holes_cutout:
    - what: circle
      where: true
      radius: 7
  mock_pcb:
    [ board, -_switch_mount_holes_cutout ]
  _battery_dimension:
    - what: rectangle
      where:
        ref: main_index_bot
        shift: [0, -15]
        rotate: -10
      size: [30, 12]
  battery_cutout:
    [ switch_plate, -_battery_dimension ]
pcbs:
  top:
    template: kicad8
    outlines:
      main:
        outline: switch_plate
  bottom:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      flavorText:
        what: ceoloide/utility_text
        params:
          text: "Louis XVI"
          reversible: true
          width: 20
          height: 25
          bold: true
          italic: true
        where:
          ref: [main_middle_bot]
      holeTopLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [main_outer_top]
          shift: [0.55kx, -0.3ky]
      holeTopRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [main_inner_top]
          shift: [-0.55kx, -0.3ky]
      holeBotLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [main_outer_bot]
          shift: [0.55kx, -0.3ky]
      holeBotMid:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [thumb_2_low]
          shift: [0.55kx, -0.3ky]
      holeBotRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: [thumb_5_high]
          shift: [-0.6kx, -0.3ky]
  louisXVI:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      choc:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          reversible: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          reversible: true
          include_thru_hole_smd_pads: true
          include_traces_vias: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      controller:
        what: ceoloide/mcu_nice_nano
        params:
          reversible: true
        where:
          ref: main_inner_top
          shift: [20, -8]
      screen:
        what: ceoloide/display_nice_view
        params:
          reversible: true
          CS:   P1
          MOSI: P2
          SCK:  P3
        where:
          ref: main_inner_mid
          shift: [1kx+2, 5]
      battery:
        what: ceoloide/battery_connector_molex_pico_ezmate_1x02
        params:
          reversible: true
          BAT_P: BAT_P
          BAT_N: GND
        where:
          ref: main_inner_bot
          shift: [1kx+3, -2]
          rotate: -90
      power_switch:
        what: ceoloide/power_switch_smd_side
        params:
          reversible: true
        where:
          ref: thumb_5_high
          shift: [-10, 9.5]
          rotate: 88
      reset:
        what: ceoloide/reset_switch_smd_side
        params:
          reversible: true
          from: GND
          to: RST
        where:
          ref: main_inner_bot
          shift: [1.5kx+1, -3]
          rotate: -90
      holeTopLeft:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: moutingHoleSize
          hole_drill: moutingHoleSize
        where:
          ref: [main_outer_top]
          shift: [0.55kx, -0.3ky]
      holeTopRight:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: moutingHoleSize
          hole_drill: moutingHoleSize
        where:
          ref: [main_inner_top]
          shift: [-0.55kx, -0.3ky]
      holeBotLeft:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: moutingHoleSize
          hole_drill: moutingHoleSize
        where:
          ref: [main_outer_bot]
          shift: [0.55kx, -0.3ky]
      holeBotMid:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: moutingHoleSize
          hole_drill: moutingHoleSize
        where:
          ref: [thumb_2_low]
          shift: [0.55kx, -0.3ky]
      holeBotRight:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: moutingHoleSize
          hole_drill: moutingHoleSize
        where:
          ref: [thumb_5_high]
          shift: [-0.6kx, -0.3ky]
cases:
  _xlBottom:
    - name: xlBoard
      extrude: baseThickness
  _outerWall:
    - name: xlBoard
      extrude: caseThickness
  _innerWall:
    - name: board
      extrude: caseThickness
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: _mountingHoles
      extrude: baseThickness
  bottom:
    - name: board
      extrude: baseThickness
    - what: case
      name: _holes
      operation: subtract
  topPlate:
    - what: outline
      name: switch_plate
      extrude: baseThickness
    - what: case
      name: wall
      operation: add
      shift: [0, 0, -caseThickness+baseThickness]
  mirrorTop:
    - what: outline
      name: switch_plate
      extrude: baseThickness
    - what: case
      name: wall
      operation: add
      shift: [0, 0, 0]
  _mockHoles:
    - name: _mountingHoles
      extrude: pcbThickness
  mockPcb:
    - what: outline
      name: mock_pcb
      extrude: pcbThickness
    - what: case
      name: _mockHoles
      operation: subtract
  fullBuild:
    - what: case
      name: topPlate
    - what: case
      name: mockPcb
      operation: add
      shift: [0, 0, -4.2]
    - what: case
      name: bottom
      shift: [0, 0, -6.2]